---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install httpd
    yum: name=httpd state=present
  - name: start httpd
    service: name=httpd state=started
  - name: install docker
    yum: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    yum: name=git state=present 
  - name: Build Dockerfile
    command:  docker build  -t phpapp:v1 .
  - name: run Image
    command: docker run -itd -p 8083:80 phpapp:v1
